function theCatchErr() {
  return { success: false, message: "Internal Server Error!" };
}
module.exports = { theCatchErr };
